# This config uses the `.circleci/extended/orb-test.yml` as its base, and then publishes the app to S3.
# The workflow contained here demonstrates a practical application of `post-steps`
# and using workspace persistence
version: 2.1

# Orbs are reusable packages of CircleCI configuration that you may share across projects, enabling you to create encapsulated, parameterized commands, jobs, and executors that can be used across multiple projects.
# See: https://circleci.com/docs/2.0/orb-intro/
orbs:
  eb: circleci/aws-elastic-beanstalk@2.0.0
  node: circleci/node@5
  # The S3 orb will setup the aws-cli and quickly copy or sync anything to s3.
  # Orbs reduce the amount of configuration required for common tasks.
  # See the orb documentation here: https://circleci.com/developer/orbs/orb/circleci/aws-s3
  # NOTE: Environment variables containing the necessary secrets can be setup in the CircleCI UI
  # See here https://circleci.com/docs/2.0/env-vars/#setting-an-environment-variable-in-a-project
  aws-s3: circleci/aws-s3@2.0
# Invoke jobs via workflows
# See: https://circleci.com/docs/2.0/configuration-reference/#workflows
workflows:
  sample: # This is the name of the workflow, feel free to change it to better match your workflow.
    # Inside the workflow, you define the jobs you want to run.
    jobs:
      - node/run:
          name: Frontend CICD
          npm-run: build
          version: "15.1"
          app-dir: udagram-frontend
          # after the node/test job completes, build the dist packages and save them to a workspace
          post-steps:
            - aws-s3/copy:
                from: udagram-frontend/www/
                to: s3://udagram-fe
                arguments: --recursive
      - node/run:
          name: Backend CICD
          npm-run: build
          version: "15.1"
          app-dir: udagram-api
          post-steps:
            - eb/setup
            - run:
                command: cd udagram-api/www && eb init udagram-backend -r $AWS_DEFAULT_REGION -p node.js && eb deploy Udagrambackend-env-1


