version: 2.1

orbs:
  # The elastic beanstalk orb is used to deploy backend build to AWS EB
  eb: circleci/aws-elastic-beanstalk@2.0.0
  # The node orb is used to install dependecies, build and cache for other calls
  node: circleci/node@5
# The S3 orb will setup the aws-cli and quickly copy or sync anything to s3.
  aws-s3: circleci/aws-s3@2.0
# Invoke jobs via workflows
# See: https://circleci.com/docs/2.0/configuration-reference/#workflows
workflows:
  CICD: 
    jobs:
      - node/run:
          name: Install packages
          npm-run: install
          version: "15.1"
      - node/run:
          name: Test
          npm-run: test
          version: "15.1"
      - node/run:
          name: Build
          npm-run: build
          version: "15.1"
          post-steps:
            - aws-s3/copy:
                from: udagram-frontend/www/
                to: s3://udagram-fe
                arguments: --recursive
            - eb/setup
            - run:
                command: cd udagram-api/www && eb init udagram-backend -r $AWS_DEFAULT_REGION -p node.js && eb setenv AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID AWS_DEFAULT_REGION=$AWS_DEFAULT_REGION AWS_REGION=$AWS_REGION AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY DATABASE_PORT=$DATABASE_PORT JWT_SECRET=$JWT_SECRET PORT=$PORT POSTGRES_DB=$POSTGRES_DB POSTGRES_HOST=$POSTGRES_HOST POSTGRES_PASSWORD=$POSTGRES_PASSWORD POSTGRES_USERNAME=$POSTGRES_USERNAME URL=$URL && eb deploy Udagrambackend-env-1 && aws s3 cp udagram-frontend/www/ s3://udagram-fe --recursive