version: 2.1

orbs:
  # The elastic beanstalk orb is used to deploy backend build to AWS EB
  eb: circleci/aws-elastic-beanstalk@2.0.0
  # The node orb is used to install dependecies, build and cache for other calls
  node: circleci/node@5
# The S3 orb will setup the aws-cli and quickly copy or sync anything to s3.
  aws-s3: circleci/aws-s3@2.0
# Invoke jobs via workflows
# See: https://circleci.com/docs/2.0/configuration-reference/#workflows
workflows:
  CICD: 
    jobs:
      - node/run:
          name: Frontend CICD
          npm-run: build
          version: "15.1"
          app-dir: udagram-frontend
          # Build and push  to aws s3 fe bucket
          post-steps:
            - aws-s3/copy:
                from: udagram-frontend/www/
                to: s3://udagram-fe
                arguments: --recursive
      - node/run:
          name: Backend CICD
          npm-run: build
          version: "15.1"
          app-dir: udagram-api
          # Build, setup eb and push to backend EC2
          post-steps:
            - eb/setup
            - run:
                command: cd udagram-api/www && eb init udagram-backend -r $AWS_DEFAULT_REGION -p node.js && eb deploy Udagrambackend-env-1


